# Generated by Django 4.1.7 on 2023-03-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpost',
            options={'ordering': ['user_id']},
        ),
    ]
